const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const context=vm.createContext({});
vm.runInContext(fs.readFileSync('cycles.js','utf8'),context);
vm.runInContext(fs.readFileSync('live-timers.js','utf8'),context);
const cycles=context.TennoCycles;
const now=Date.now(),world=phase=>({cetusCycle:{isDay:phase,expiry:new Date(now+(phase?60000:120000)).toISOString()}});
const first=cycles.snapshot(world(true),now),second=cycles.snapshot(world(false),now);
assert.equal(cycles.changes(null,first).length,0,'first observation is silent');
assert.equal(cycles.changes(first,second,now+61000)[0].key,'cetusCycle');
assert.equal(cycles.changes(second,second).length,0,'repeated response is silent');
assert.equal(cycles.changes(second,first).length,0,'older response is silent');
assert.equal(Object.keys(cycles.snapshot(world(true),now+180000)).length,0,'expired data ignored');
assert.equal(cycles.preferences({volume:Infinity}).volume,0.5);
assert.equal(cycles.preferences({volume:9}).volume,1);
assert.equal(cycles.preferences().enabled,false);
assert.equal(Object.values(cycles.preferences().cycles).some(Boolean),false);
assert.equal(cycles.preferences().speech,true);
assert.equal(cycles.preferences().voicePack,'cephalon');
assert.equal(cycles.packClip('cetusCycle','NIGHT'),'assets/voice/cephalon/cetusCycle-night.wav');
assert.equal(cycles.packClip('cetusCycle','../../bad'),null);
for (const row of JSON.parse(fs.readFileSync('assets/voice/cephalon/lines.json','utf8'))) {
 const clip=cycles.packClip(row.key,row.phase);
 assert.ok(clip);
 assert.equal(fs.readFileSync(clip).toString('ascii',0,4),'RIFF');
}
assert.equal(cycles.announcement('vallisCycle','cold',0.4).text,'Cycle changed at Fortuna / Orb Vallis on Venus to cold.');
assert.equal(cycles.announcement('vallisCycle','cold',0.4).options.volume,0.4);
assert.equal(cycles.announcement('vallisCycle','cold').options.enqueue,true);
assert.equal(cycles.announcement('cambionCycle','vome').text,'Cycle changed at Necralisk / Cambion Drift on Deimos to vome.');
assert.equal(cycles.announcement('duviriCycle','joy').options.pitch,1);
assert.equal(cycles.announcement('cambionCycle','vome').options.pitch,1);
assert.throws(()=>cycles.announcement('unknown','day'));
assert.throws(()=>cycles.announcement('cetusCycle','<speak>day</speak>'));
assert.equal(cycles.changes(first,second,now+1000).length,0,'early phase corrections are silent');
assert.equal(cycles.changes(first,second,now+400000).length,0,'old transitions after sleep are silent');
assert.equal(cycles.snapshot({cetusCycle:{state:'bogus',expiry:new Date(now+60000).toISOString()}},now).cetusCycle,undefined);
assert.equal(cycles.snapshot({cetusCycle:{state:'night',activation:new Date(now+10000).toISOString(),expiry:new Date(now+60000).toISOString()}},now).cetusCycle,undefined);
const manifest=JSON.parse(fs.readFileSync('manifest.json','utf8'));
assert.ok(manifest.content_scripts[0].matches.includes('https://wiki.warframe.com/*'));
assert.ok(manifest.web_accessible_resources[0].matches.includes('https://wiki.warframe.com/*'));
assert.equal(cycles.definitions.length,5);
assert.equal(cycles.preferences({cycles:{earthCycle:true}}).cycles.cetusCycle,true,'legacy Earth selection migrates');
assert.equal(cycles.preferences({cycles:{earthCycle:true}}).cycles.earthCycle,undefined);
assert.equal(cycles.packClip('earthCycle','night'),null,'legacy audio cannot be played');
assert.equal(cycles.snapshot({earthCycle:{state:'day',expiry:new Date(now+60000).toISOString()}},now).earthCycle,undefined);
assert.equal(cycles.mergeSnapshot({earthCycle:{phase:'day',expiry:now+60000}},{}).earthCycle,undefined);
assert.equal(cycles.mergeSnapshot(first,second,now+1000).cetusCycle.phase,'day','early correction does not consume a later valid change');
assert.equal(cycles.changes(cycles.mergeSnapshot(first,second,now+1000),second,now+61000).length,1);
assert.equal(cycles.mergeSnapshot(first,{cetusCycle:{phase:'night',expiry:first.cetusCycle.expiry}},now+61000).cetusCycle.phase,'day','same-expiry phase corrections are ignored');
assert.equal(cycles.snapshot({cetusCycle:{state:'day',expiry:new Date(now+86400000).toISOString()}},now).cetusCycle,undefined,'implausible API timestamps are rejected');
const fixture=JSON.parse(fs.readFileSync('tests/fixtures/cycles-api.json','utf8').replace(/^\uFEFF/,''));
const observed=cycles.snapshot(fixture.world,Date.parse(fixture.capturedAt));
assert.deepEqual(Object.keys(observed).sort(),Array.from(cycles.definitions,row=>row.key).sort(),'current public API shape supports every tracked cycle');
const lines=JSON.parse(fs.readFileSync('assets/voice/cephalon/lines.json','utf8'));
assert.equal(lines.length,13);
assert.equal(lines.some(row=>row.key==='earthCycle'),false);
assert.equal(manifest.permissions.includes('tts'),false,'bundled speech requires no system TTS permission');
let saved={},alerts=[],messages=[],spoken=[],listener,alarm;
const chrome={runtime:{onMessage:{addListener(fn){listener=fn;}},getURL:p=>p,getContexts:async()=>[],sendMessage:async m=>{messages.push(m);return {ok:true};}},
 storage:{local:{get:async()=>({tennoLinkState:structuredClone(saved)}),set:async value=>{saved=structuredClone(value.tennoLinkState);}}},
 notifications:{create:async(id,value)=>alerts.push({id,value})},alarms:{onAlarm:{addListener(fn){alarm=fn;}},create:async()=>{},clear:async()=>{}},offscreen:{createDocument:async()=>{},closeDocument:async()=>{}}};
chrome.tts={getVoices:callback=>callback([{voiceName:'Remote',lang:'en-US',remote:true},{voiceName:'Local',lang:'en-US',remote:false}]),
 speak:(text,options,callback)=>{spoken.push({text,options});callback();}};
let clockNow=now;
class TestDate extends Date { static now(){return clockNow;} }
Object.assign(context,{chrome,Date:TestDate,importScripts(){},console,AbortSignal:{timeout:()=>undefined}});
vm.runInContext(fs.readFileSync('background.js','utf8'),context);
(async()=>{
 saved.cycleNotifications={enabled:true,sound:true,speech:false,cycles:{cetusCycle:true}};
 context.worldInput=world(true);
 await vm.runInContext('processCycleChanges(worldInput)',context);
 assert.equal(alerts.length,0);
 clockNow=now+61000;
 context.worldInput=world(false);
 await vm.runInContext('processCycleChanges(worldInput)',context);
 assert.equal(alerts.length,1);
 assert.equal(messages[0].type,'PLAY_CYCLE_SOUND');
 await vm.runInContext('processCycleChanges(worldInput)',context);
 assert.equal(alerts.length,1);
 clockNow=now+130000;
 saved.cycleNotifications.enabled=false;
 context.worldInput={cetusCycle:{state:'day',expiry:new Date(now+240000).toISOString()}};
 await vm.runInContext('processCycleChanges(worldInput)',context);
 assert.equal(alerts.length,1);
 clockNow=now+241000;
 saved.cycleNotifications={enabled:true,speech:true,sound:false,voicePack:'system',volume:0.3,cycles:{cetusCycle:true}};
 context.worldInput={cetusCycle:{state:'night',expiry:new Date(now+300000).toISOString()}};
 await vm.runInContext('processCycleChanges(worldInput)',context);
 assert.equal(spoken.length,0,'old system preferences migrate to the companion pack');
 assert.equal(messages.at(-1).type,'PLAY_CYCLE_VOICE');
 assert.equal(messages.at(-1).chime,false,'speech without chime remains available');
 assert.equal(alerts.at(-1).value.silent,true);
 assert.equal(saved.cycleNotificationHistory[0].audio,'Announcement');
 assert.equal(saved.cycleNotificationHistory[0].status,'delivered');
 // A lagging API response must not roll back the persisted baseline.
 context.worldInput=world(false);
 await vm.runInContext('processCycleChanges(worldInput)',context);
 assert.equal(saved.cycleSnapshot.cetusCycle.expiry,now+300000);
 assert.equal(alerts.length,2);
 // Simultaneous requests serialize detection and cannot alert twice.
 clockNow=now+301000;
 context.worldInput={cetusCycle:{state:'day',activation:new Date(now+300000).toISOString(),expiry:new Date(now+420000).toISOString()}};
 await vm.runInContext('Promise.all([processCycleChanges(worldInput),processCycleChanges(worldInput)])',context);
 assert.equal(alerts.length,3);
 // Background alarm fetches public world state with no dashboard or page involved.
 clockNow=now+421000;
 let fetched=0;
 context.fetch=async()=>{fetched++;return {ok:true,json:async()=>({cetusCycle:{state:'night',activation:new Date(now+420000).toISOString(),expiry:new Date(now+480000).toISOString()}})};};
 alarm({name:'tenno-cycle-check'});
 await new Promise(resolve=>setImmediate(resolve));
 await vm.runInContext('cycleCheckQueue',context);
 assert.equal(fetched,1);
 assert.equal(alerts.length,4,'closed-panel background alarm delivers a transition');
 const ensure=await new Promise(resolve=>listener({type:'ENSURE_CYCLE_MONITOR'},{url:'https://wiki.warframe.com/w/Earth'},resolve));
 assert.equal(ensure.ok,true);
 const rejected=await new Promise(resolve=>listener({type:'ENSURE_CYCLE_MONITOR'},{url:'https://example.com/'},resolve));
 assert.equal(rejected.ok,false);
 const beforeSettings=structuredClone(saved.cycleSnapshot);
 const updatedPreferences={...saved.cycleNotifications,volume:0.8};
 const settingsResult=await new Promise(resolve=>listener({type:'SAVE_CYCLE_NOTIFICATIONS',preferences:updatedPreferences},null,resolve));
 assert.equal(settingsResult.ok,true);
 assert.deepEqual(saved.cycleSnapshot,beforeSettings,'volume changes preserve transition baseline');
 assert.equal(alerts.length,4,'saving settings does not replay an alert');
 let scheduled=null,created=0;
 chrome.alarms.get=async()=>scheduled;
 chrome.alarms.create=async(name,options)=>{created++;scheduled={name,...options};};
 await vm.runInContext('configureCycleAlarm()',context);
 await vm.runInContext('configureCycleAlarm()',context);
 assert.equal(created,1,'missing alarm is restored; existing alarm is not postponed');
 saved.cycleNotifications={enabled:true,sound:false,speech:false,cycles:{cetusCycle:true}};
 clockNow=now+481000;
 context.worldInput={cetusCycle:{state:'day',activation:new Date(now+480000).toISOString(),expiry:new Date(now+600000).toISOString()}};
 const soundsBefore=messages.length;
 await vm.runInContext('processCycleChanges(worldInput)',context);
 assert.equal(alerts.at(-1).value.silent,true,'all-audio-off suppresses the OS notification sound too');
 assert.equal(messages.length,soundsBefore);
 const packPreview=await new Promise(resolve=>listener({type:'PREVIEW_CYCLE_SPEECH',key:'duviriCycle',voicePack:'cephalon',volume:0.6},null,resolve));
 assert.equal(packPreview.ok,true);
 assert.equal(messages.at(-1).type,'PLAY_CYCLE_VOICE');
 assert.equal(messages.at(-1).phase,'joy');
 const preview=await new Promise(resolve=>listener({type:'PREVIEW_CYCLE_SPEECH',key:'duviriCycle',volume:0.6},null,resolve));
 assert.equal(preview.ok,true);
 assert.equal(messages.at(-1).type,'PLAY_CYCLE_VOICE');
 assert.equal(messages.at(-1).chime,true);
 console.log('cycles.test.cjs: phase detection, stale data, preferences and delivery passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
